"""add account_video_snapshots + min_views setting

Revision ID: 6286b547f27f
Revises: c0a28babd8ae
Create Date: 2026-07-06 10:17:50.034636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6286b547f27f'
down_revision: Union[str, Sequence[str], None] = 'c0a28babd8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_video_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_video_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_video_id'], ['account_videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_video_id', 'captured_at')
    )
    op.create_index(op.f('ix_account_video_snapshots_account_video_id'), 'account_video_snapshots', ['account_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_video_snapshots_account_video_id'), table_name='account_video_snapshots')
    op.drop_table('account_video_snapshots')
    # ### end Alembic commands ###
