"""initial schema (clippers, accounts, videos, payouts)

Revision ID: c0a28babd8ae
Revises: 
Create Date: 2026-07-06 10:00:50.728522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a28babd8ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('clippers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payout_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clipper_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('profile_url', sa.String(length=700), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_status', sa.String(length=30), nullable=True),
    sa.Column('last_fetch_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('views_at_last_payout_checkpoint', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clipper_id'], ['clippers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_url')
    )
    op.create_index(op.f('ix_accounts_clipper_id'), 'accounts', ['clipper_id'], unique=False)
    op.create_table('payout_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_cycle_id', sa.Integer(), nullable=False),
    sa.Column('clipper_id', sa.Integer(), nullable=False),
    sa.Column('delta_views', sa.Integer(), nullable=False),
    sa.Column('amount_due_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clipper_id'], ['clippers.id'], ),
    sa.ForeignKeyConstraint(['payout_cycle_id'], ['payout_cycles.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_line_id'], ['payout_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_lines_clipper_id'), 'payout_lines', ['clipper_id'], unique=False)
    op.create_index(op.f('ix_payout_lines_payout_cycle_id'), 'payout_lines', ['payout_cycle_id'], unique=False)
    op.create_table('account_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform_video_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=700), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'platform_video_id')
    )
    op.create_index(op.f('ix_account_videos_account_id'), 'account_videos', ['account_id'], unique=False)
    op.create_table('account_view_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'captured_at')
    )
    op.create_index(op.f('ix_account_view_snapshots_account_id'), 'account_view_snapshots', ['account_id'], unique=False)
    op.create_table('payout_line_account_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_line_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('delta_views', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['payout_line_id'], ['payout_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_line_account_details_payout_line_id'), 'payout_line_account_details', ['payout_line_id'], unique=False)
    op.create_table('payout_line_account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_line_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('start_views', sa.Integer(), nullable=False),
    sa.Column('end_views', sa.Integer(), nullable=False),
    sa.Column('delta_views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['payout_line_id'], ['payout_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_line_account_snapshots_payout_line_id'), 'payout_line_account_snapshots', ['payout_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payout_line_account_snapshots_payout_line_id'), table_name='payout_line_account_snapshots')
    op.drop_table('payout_line_account_snapshots')
    op.drop_index(op.f('ix_payout_line_account_details_payout_line_id'), table_name='payout_line_account_details')
    op.drop_table('payout_line_account_details')
    op.drop_index(op.f('ix_account_view_snapshots_account_id'), table_name='account_view_snapshots')
    op.drop_table('account_view_snapshots')
    op.drop_index(op.f('ix_account_videos_account_id'), table_name='account_videos')
    op.drop_table('account_videos')
    op.drop_index(op.f('ix_payout_lines_payout_cycle_id'), table_name='payout_lines')
    op.drop_index(op.f('ix_payout_lines_clipper_id'), table_name='payout_lines')
    op.drop_table('payout_lines')
    op.drop_index(op.f('ix_accounts_clipper_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('payout_cycles')
    op.drop_table('clippers')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
